language: node_js

services:
  - couchdb

node_js:
  - "0.10"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"

    # Workaround for Selenium #3280 issue
  - "sudo sed -i 's/^127\\.0\\.0\\.1.*$/127.0.0.1 localhost/' /etc/hosts"

    # Lets know what CouchDB we are playing with
    # and make sure its logging debug
  - "curl -X GET http://127.0.0.1:5984/"
  - "curl -X PUT http://127.0.0.1:5984/_config/log/level -d '\"debug\"'"

env:
  matrix: 
    - run=1
    - run=2
    - run=3
    - run=4
    - run=5
    - run=6
    - run=7
    - run=8
    - run=9
    - run=10
    - run=11
    - run=12
    - run=13
    - run=14
    - run=15
    - run=16
    - run=17
    - run=18
    - run=19
    - run=20